### ISSUE TITLE
Investigate using the Android SQLite bindings project to support custom SQLite builds

### ISSUE THREAD

**Issue by alipov** [yahoo/squidb#36]
Are there any plans to support [sqlcipher][1] as an underlying database?

[1]: https://github.com/sqlcipher/sqlcipher

**Comment by sbosley** [comment]
We've considered the possibility of leveraging the [Android SQLite bindings project](https://www.sqlite.org/android/doc/trunk/www/index.wiki) to allow using SquiDB with a version of SQLite other than the stock version Android ships with. I imagine the ability to use the sqlcipher extension would fall under that banner, although I don't know off the top of my head if there would be any pitfalls to using a SQLite extension rather than just a standard SQLite build. I think it's something we'd like to do at some point, but I can't commit to a definite timeline for adding it at the moment.

I'll update the issue title to reflect that we'd like to investigate the general ability to use a custom SQLite version, and we'll consider sqlcipher as one of the possible versions when we get to the point of actually working on this. Thanks for opening the issue!

**Comment by jdkoren** [comment]
@alipov On our dev_2.0 branch we just merged a PR that introduces a `squidb-sqlite-bindings` module. This module demonstrates how to use a custom SQLite implementation packaged with the APK; the module itself uses the latest official SQLite release.

When SquiDB 2.0 is released, we will also be publishing this module as an artifact for gradle. Developers who want to use some other compiled version of SQLite can pull down the module and build from source. We'll include instructions in the wiki pages at that time.

Regarding SQLCipher, we ran into some problems trying to make a similar bindings module for it. The short explanation is the SQLCipher library classes are based on outdated versions of the `android.database` classes (they appear to be from API 10), and SquiDB relies on more recent versions for correct behavior (our minimum is API 14). The differences make it unfeasible and perhaps impossible to support it at this time.

Sorry we don't have better news than this. We really would like to support this however, so we plan to reach out to the SQLCipher developers about updating their classes to match the more recent revisions of Android's. If SQLCipher does receive some updates, we'll make another attempt to support it then.

**Comment by alipov** [comment]
> On our dev_2.0 branch we just merged a PR that introduces a squidb-sqlite-bindings module.

Thanks for the update, I'll take a look.


> We really would like to support this however, so we plan to reach out to the SQLCipher developers about updating their classes to match the more recent revisions of Android's.

I'm not sure you'll be able to convince them. [They don't want to add APIs that were introduced after 2.1](https://github.com/sqlcipher/android-database-sqlcipher/issues/184#issuecomment-119954980).

**Comment by sbosley** [comment]
SquiDB 2.0 introduces the ability to connect to custom SQLite builds using the squidb-sqlite-bindings module (see [this wiki page](https://github.com/yahoo/squidb/wiki/Using-a-custom-SQLite-build) for details). SQLCipher is unfortunately still not supported due to the issues outlined above, but we've opened an issue with them to update their APIs that we'll keep an eye on.
